import {escapeHtml as e, imageMarkup, card, plainText} from './storefront.mjs';

export const trustBadges = () => `<div class="trust-badges"><a class="trust-auth" href="/pages/var-autentisering/"><img src="/assets/icons/shield.svg" width="18" height="18" alt="">Ekthetsbevis fra LegitGrails</a><a class="trust-reviews" href="/#kundeomtaler">Kundeomtaler på dagens nettsted</a></div>`;

export function homeContent(store) {
  const products=store?.products||[];
  const models=['Speedy','Keepall'].map(name=>({name,products:products.filter(p=>p.title.toLowerCase().includes(name.toLowerCase())&&p.images?.length).slice(0,4)})).filter(m=>m.products.length);
  const selected=products.filter(p=>p.images?.length).slice(0,6);
  return `<section class="model-hero"><div class="model-intro"><h1>Finn din<br>vintagefavoritt.</h1><p>Ikoniske designervesker med en historie.<br>Se detaljene. Finn den som passer deg.</p><a class="button" href="/collections/all/">Utforsk veskene</a>${trustBadges()}</div><div class="model-display"><div class="model-switch" role="group" aria-label="Velg modell">${models.map((m,i)=>`<button type="button" data-model-tab="${m.name.toLowerCase()}" aria-pressed="${i===0}" aria-controls="model-${m.name.toLowerCase()}">${m.name}</button>`).join('')}</div>${models.map((m,i)=>`<div id="model-${m.name.toLowerCase()}" class="model-panel" data-model-panel="${m.name.toLowerCase()}" ${i?'hidden':''}><div class="model-mosaic">${m.products.map((p,index)=>`<a class="model-item model-item-${index}" href="/products/${e(p.handle)}/" aria-label="Se ${e(p.title)}">${imageMarkup(p.images[0],p.title,i===0&&index===0)}</a>`).join('')}</div><a class="model-collection-link" href="/collections/${m.name.toLowerCase()}/">Utforsk ${m.name}-utvalget</a></div>`).join('')}${!models.length?'<p>Modellutvalget kunne ikke hentes. Prøv hele utvalget.</p>':''}</div></section>
  <nav class="category-paths" aria-label="Handle etter type"><a href="/collections/alle-handvesker/"><img src="/assets/icons/shopping-bag.svg" width="40" height="40" alt=""><span><strong>Håndvesker</strong><small>Finn din nye hverdagsfavoritt</small></span><img class="category-arrow" src="/assets/icons/arrow-right.svg" width="28" height="28" alt=""></a><a href="/collections/reisevesker/"><img src="/assets/icons/briefcase.svg" width="40" height="40" alt=""><span><strong>Reisevesker</strong><small>Plass til en helg borte</small></span><img class="category-arrow" src="/assets/icons/arrow-right.svg" width="28" height="28" alt=""></a></nav>
  <section class="section home-selection"><div class="section-heading"><h2>Utvalgte vesker</h2><a href="/collections/all/">Se alle vesker</a></div><p class="availability-note" data-availability-note role="status">Tilgjengelighet sjekkes …</p><div class="product-grid" data-catalog-grid>${selected.map(p=>card(p)).join('')}</div>${!selected.length?'<p>Utvalget kunne ikke hentes. Prøv igjen senere.</p>':''}</section>
  <section class="section brand-discovery" id="merker" aria-labelledby="brands-heading"><div class="brand-heading"><h2 id="brands-heading">Finn ditt merke</h2><p>Et favorittmerke. Et nytt vintagefunn.</p></div><div class="brand-links">${[...new Set(products.map(p=>p.brand).filter(Boolean))].sort().map(brand=>{const count=products.filter(p=>p.brand===brand).length;return `<a href="/collections/all/?brand=${encodeURIComponent(brand)}"><span class="brand-name">${e(brand)}</span><span class="brand-meta"><span>${count} ${count===1?'veske':'vesker'} i utvalget</span><img src="/assets/icons/arrow-right.svg" width="24" height="24" alt=""></span></a>`;}).join('')}</div></section>
  <section class="authentication-story section"><div><h2>Trygghet ligger<br>i detaljene.</h2><p>Hver vintageveske har sine særpreg. Se nærbilder, les om tilstanden og bli kjent med dokumentasjonen før du bestemmer deg.</p><a class="button" href="/pages/var-autentisering/">Slik autentiseres veskene</a></div><div class="reassurance-list"><div><h3>Uavhengig autentisering</h3><p>Vintage Designer bruker LegitGrails til å vurdere varenes ekthet.</p></div><div><h3>Dokumentert tilstand</h3><p>Les om bruksspor og se bildene av akkurat den vesken du vurderer.</p><a href="/pages/tilstandsguide/">Forstå tilstandsbeskrivelsen</a></div><div><h3>Spør om flere detaljer</h3><p>Ønsker du nærbilder eller video? Ta direkte kontakt med butikken.</p><a href="mailto:post@vintagedesigner.no">Send en e-post</a></div></div></section>
  <section class="section reviews-section" id="kundeomtaler"><div><h2>Erfaringer fra kundene</h2><p>På dagens nettsted deler kunder erfaringer med kommunikasjon, varenes tilstand og levering.</p><a href="https://vintagedesigner.no/#shopify-section-template--22805306409157__reviews_new">Les kundeomtalene hos Vintage Designer</a></div><p class="review-context">Omtalene gjelder den eksisterende butikken. Denne forhåndsvisningen tar ikke imot bestillinger.</p></section>
  <section class="section guide-discovery"><div><h2>Bli kjent med klassikerne</h2><a href="/blogs/blog/">Utforsk journal og guider</a></div><a href="/blogs/blog/louis-vuitton-speedy-30-vs-35-hvilken-storrelse-passer-deg/">Speedy 30 eller 35?<span>Finn størrelsen som passer deg</span></a><a href="/pages/sokeoppdrag/">På jakt etter noe spesielt?<span>La butikken hjelpe deg å lete</span></a></section>`;
}

export function productFacts(value) {
  const text=plainText(value).replace(/\s+(?=(?:Tilstand|Stand|Mål|Dimensjoner|Produksjonskode|Datokode|Årstall|Årgang|Inkludert|Tilbehør|Følger med|Medfølger)\s*:)/gi,'\n');
  const fields=[];
  const patterns=[['Tilstand',/(?:^|\s)(?:Tilstand|Stand)\s*:\s*([^\n.]{1,85})/i],['Mål',/(?:^|\s)(?:Mål|Dimensjoner)\s*(?::|ca\.?)?\s*([\d][^\n.]{3,150}(?:\.[\d][^\n.]{0,100})?)/i],['Produksjonskode',/(?:Produksjonskode|Datokode)\s*:\s*([A-Z0-9 -]{3,24})\b/i],['År',/(?:Årstall|Årgang|Produsert i)\s*:?\s*((?:19|20)\d{2})/i],['Medfølger',/(?:Inkludert|Tilbehør|Følger med|Medfølger)\s*:\s*([^\n.]{1,150})/i]];
  for(const [label,re] of patterns){const match=text.match(re);if(match){let value=match[1].trim();if(label==='Produksjonskode')value=value.split(/\s/)[0];if(label==='Tilstand'){const grade=value.match(/^(?:[\p{L}-]+\s+){0,3}stand\b/iu);if(grade)value=grade[0];}fields.push([label,value]);}}
  const dimensions=text.match(/(?:Mål|Dimensjoner)\s*:?\s*(?:ca\.?\s*)?([\d][^\n]{2,150}?)(?=\.(?:\s|$)|\n|$)/i);
  if(dimensions){const existing=fields.findIndex(([label])=>label==='Mål');if(existing>=0)fields.splice(existing,1);fields.push(['Mål',dimensions[1].trim()]);}
  return fields;
}

export function readableDescription(value) {
  return plainText(value).replace(/([^\n])\s*(?=(?:Tilstand:|Yttermateriale:|Innside:|Detaljer:|Produksjonskode:|Medfølgende:|Medfølger:|Dette er en vintage veske))/g,'$1\n').replace(/\n{3,}/g,'\n\n');
}

export function authenticationContent(){return `<article class="section editorial authentication-page"><p class="eyebrow">Vintage Designer</p><h1>Ekthet skal ikke<br>være et spørsmål.</h1><p class="editorial-lead">Vintage Designer opplyser at hver vare vurderes av LegitGrails, en uavhengig tjeneste for autentisering av designervarer.</p><div class="auth-process"><h2>Fra detaljbilder til dokumentasjon</h2><ol><li><h3>Varen undersøkes</h3><p>Butikken inspiserer varen og tar detaljbildene som trengs for vurderingen.</p></li><li><h3>LegitGrails vurderer ektheten</h3><p>Bildene undersøkes av autentiseringstjenesten før varen godkjennes.</p></li><li><h3>Et digitalt bevis følger kjøpet</h3><p>Butikken opplyser at dokumentasjonen sendes på e-post ved kjøp på dagens nettsted.</p></li></ol></div><section class="certificate-info"><h2>Dokumentasjon du kan kontrollere</h2><p>Et ektehetsbevis har en unik ID og QR-kode. Du kan kontrollere et eksisterende bevis hos LegitGrails; denne forhåndsvisningen utsteder ingen sertifikater.</p><a class="button" href="https://certificates.legitgrails.com/">Kontroller et ektehetsbevis</a></section><details><summary>Hva får jeg vite om akkurat min veske?</summary><p>Produktbeskrivelsen viser opplysninger om tilstand og detaljer som butikken har dokumentert. Spør butikken om bilder og bevis for den konkrete varen.</p></details><details><summary>Hvor finner jeg butikkens fullstendige vilkår?</summary><p><a href="https://vintagedesigner.no/pages/var-autentisering">Les den fullstendige autentiseringsinformasjonen på dagens nettsted.</a></p></details><p><a href="/pages/tilstandsguide/">Les også om tilstand og bruksspor</a></p></article>`;}
